version: "3.8"
services: 
        node:
                build: .
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
                        


